

start_position = {
  'WP8': {'name': 'WP8', 'color': 'white', 'location': '01', 'pic':'WP.png', 'notMoved': True},
  'WP7': {'name': 'WP7', 'color': 'white', 'location': '11', 'pic':'WP.png', 'notMoved': True},
  'WP6': {'name': 'WP6', 'color': 'white', 'location': '21', 'pic':'WP.png', 'notMoved': True},
  'WP5': {'name': 'WP5', 'color': 'white', 'location': '31', 'pic':'WP.png', 'notMoved': True},
  'WP4': {'name': 'WP4', 'color': 'white', 'location': '41', 'pic':'WP.png', 'notMoved': True},
  'WP3': {'name': 'WP3', 'color': 'white', 'location': '51', 'pic':'WP.png', 'notMoved': True},
  'WP2': {'name': 'WP2', 'color': 'white', 'location': '61', 'pic':'WP.png', 'notMoved': True},
  'WP1': {'name': 'WP1', 'color': 'white', 'location': '71', 'pic':'WP.png','notMoved': True},
  'BP8': {'name': 'BP8', 'color': 'black', 'location': '06', 'pic':'BP.png', 'notMoved': True},
  'BP1': {'name': 'BP1', 'color': 'black', 'location': '16', 'pic':'BP.png', 'notMoved': 'true'},
  'BP2': {'name': 'BP2', 'color': 'black', 'location': '26', 'pic':'BP.png', 'notMoved': True},
  'BP3': {'name': 'BP3', 'color': 'black', 'location': '36', 'pic':'BP.png', 'notMoved': True},
  'BP4': {'name': 'BP4', 'color': 'black', 'location': '46', 'pic':'BP.png', 'notMoved': True},
  'BP5': {'name': 'BP5', 'color': 'black', 'location': '56', 'pic':'BP.png', 'notMoved': True},
  'BP6': {'name': 'BP6', 'color': 'black', 'location': '66', 'pic':'BP.png', 'notMoved': True},
  'BP7': {'name': 'BP7', 'color': 'black', 'location': '76', 'pic':'BP.png', 'notMoved': True},
  'WR1': {'name': 'WR1', 'color': 'white', 'location': '00', 'pic':'WR.png', 'notMoved': True},
  'WR2': {'name': 'WR2', 'color': 'white', 'location': '70', 'pic':'WR.png', 'notMoved': True},
  'BR1': {'name': 'BR1', 'color': 'black', 'location': '07', 'pic':'BR.png', 'notMoved': True},
  'BR2': {'name': 'BR2', 'color': 'black', 'location': '77', 'pic':'BR.png', 'notMoved': True},
  'WB1': {'name': 'WB1', 'color': 'white', 'location': '10', 'pic':'WB.png', 'notMoved': True},
  'WB2': {'name': 'WB2', 'color': 'white', 'location': '60', 'pic':'WB.png', 'notMoved': True},
  'BB1': {'name': 'BB1', 'color': 'black', 'location': '17', 'pic':'BB.png', 'notMoved': True},
  'BB2': {'name': 'BB2', 'color': 'black', 'location': '67', 'pic':'BB.png', 'notMoved': True},
  'WKN1': {'name': 'WKN1', 'color': 'white', 'location': '20', 'pic':'WK.png', 'notMoved': True},
  'WKN2': {'name': 'WKN2', 'color': 'white', 'location': '50', 'pic':'WK.png', 'notMoved': True},
  'BKN1': {'name': 'BKN1', 'color': 'black', 'location': '27', 'pic':'BK.png', 'notMoved': True},
  'BKN2': {'name': 'BKN2', 'color': 'black', 'location': '57', 'pic':'BK.png', 'notMoved': True},
  'WQ': {'name': 'WQ', 'color': 'white', 'location': '30', 'pic':'WQ.png', 'notMoved': True},
  'BQ': {'name': 'BQ', 'color': 'black', 'location': '37', 'pic':'BQ.png', 'notMoved': True},
  'BKing': {'name': 'BKing', 'color': 'black', 'location': '47', 'pic':'BKing.png', 'notMoved': True},
  'WKing': {'name': 'WKing', 'color': 'white', 'location': '40', 'pic':'WKing.png', 'notMoved': True}
}